### PR TITLE
Add python_requires 2.7 or 3.6+ to setup.py

### PR DESCRIPTION
**Pull request by matthewfeickert**
This will make it clear to PyPI what Python requires are needed and also make it clear to the user when they try to install it.

This PR also adds classifier metadata for PyPI.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Given what @lgray had mentioned at the coffee break, I force pushed a change that also allows support for Python 2.7

**Comment by andrzejnovak** [comment]
@matthewfeickert Not necessarily. Is there a good case not to? I thought it was pretty much a python standard.

**Comment by matthewfeickert** [comment]
> Not necessarily. Is there a good case not to? I thought it was pretty much a python standard.

Yes, but a lot of people also think that 79 chars is too restrictive. pyhf formats with Black, and there [we use 88 lines](https://github.com/diana-hep/pyhf/blob/master/pyproject.toml#L2) as that seems to be a more reasonable length and it what the original author of Black recommends.

**Comment by matthewfeickert** [comment]
@andrzejnovak I think we've broken all of the CI by merging this in now though. We'll have to open up another PR that changes the line length that signals an error.

**Comment by matthewfeickert** [comment]
Ah no! I see that you are steps ahead of me and have already done this in https://github.com/andrzejnovak/mplhep/commit/521e160b13261089352114cc650958307c2a498c. :) Thanks!

**Pull request merged**
